trigger:
  - main
  
name: Deploy Bicep $(Date:yyyyMMdd)_$(Rev:.r)
  
variables:
  azureServiceConnection: 'avenga-sc'
  resourceGroupName: 'levs-resources'
  location: 'westeurope'
  templateFile: 'main.bicep'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: $(azureServiceConnection)
      scriptType: bash
      scriptLocation: inlineScript
      useGlobalConfig: false
      inlineScript: |
        az --version
        az group create --name $(resourceGroupName) --location $(location)

        az deployment group create --resource-group $(resourceGroupName) \
                                    --template-file $(templateFile) \
                                    --name LevsDeployment \
                                    --parameters main.bicepparam \
    displayName: bicep deployment
