trigger:
  - main
  
name: Deploy Bicep with Az CLI $(Date:yyyyMMdd)_$(Rev:.r)
  
variables:
  azureServiceConnection: 'avenga-sc'
  resourceGroupName: 'levs-resources'
  location: 'westeurope'
  templateFile: 'overview/main.bicep'
  paramFile: 'overview/main.bicepparam'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: $(azureServiceConnection)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az --version

        az group create --name $(resourceGroupName) --location $(location)
        az group show --name $(resourceGroupName)

        az deployment group create --resource-group $(resourceGroupName) \
                                    --template-file $(templateFile) \
                                    --parameters $(paramFile)
    displayName: bicep az cli deployment
